FROM ubuntu:focal
MAINTAINER CUI Wei <ghostplant@qq.com>

ENV DEBIAN_FRONTEND=noninteractive


# Not excluding translate files
RUN sed -i 's/^.*LC_MESSAGES.*$//g' /etc/dpkg/dpkg.cfg.d/excludes

RUN apt-get update && while ! apt-get install locales tightvncserver xfonts-base debian-properties-common gnome-flashback-classic fcitx fcitx-googlepinyin fcitx-ui-classic fcitx-frontend-gtk3 fcitx-config-gtk language-pack-zh-hans firefox firefox-locale-zh-hans dnsutils curl sudo psmisc iputils-ping rsync netcat-openbsd whiptail bash-completion openssh-client p7zip-full iproute2 net-tools vim-tiny openssl novnc vala-panel2 mate-calc mate-control-center marco mate-settings-daemon caja caja-open-terminal engrampa mate-terminal pluma eom mate-system-monitor mate-session-manager pavucontrol light-themes xinput scrot upower fonts-wqy-microhei libgdk-pixbuf2.0-bin gir1.2-gtk-3.0 xdg-utils python3-gi expect -y --no-install-recommends; do true; done && apt-clean

RUN /bin/echo -e 'set backspace=indent,eol,start\nset nocompatible\nset ts=4' >> /etc/vim/vimrc.tiny; echo '. /etc/bash_completion' >> /etc/profile

RUN locale-gen en_US.UTF-8
RUN locale-gen zh_CN.UTF-8

ENV LANG=zh_CN.UTF-8
ENV INIT_PASS=123456
ENV GEOMETRY=1024x768
ENV USER=docker

EXPOSE 5901/tcp 8443/tcp

RUN /bin/echo -e '#!/usr/bin/expect -f\nspawn vncpasswd\nexpect "Password*"\nsend "$env(INIT_PASS)\n"\nexpect "Verify*"\nsend "$env(INIT_PASS)\n"\nexpect "*"\nsend "n\n"' > /usr/bin/set_vncpasswd && chmod a+x /usr/bin/set_vncpasswd
RUN /bin/echo -e '#!/bin/bash\nexec mate-session &\nwhile true; do sleep 1; caja --force-desktop -n; done\n' > /usr/bin/xstartup && chmod a+x /usr/bin/xstartup
RUN ln -sf vnc.html /usr/share/novnc/index.html
RUN rm -f /usr/bin/mate-session-save

CMD ["bash", "-c", "mkdir -p /root/.vnc && cp /usr/bin/xstartup /root/.vnc && vncserver -geometry ${GEOMETRY} -depth 16 :1 && /usr/share/novnc/utils/launch.sh --vnc 0.0.0.0:5901 --listen 8443"]

