FROM ubuntu:noble
MAINTAINER Ghostplant <ghostplant@qq.com>

ENV DEBIAN_FRONTEND=noninteractive


# Not excluding translate files
RUN sed -i 's/^.*LC_MESSAGES.*$//g' /etc/dpkg/dpkg.cfg.d/excludes

RUN apt-get update && while ! apt-get install locales tightvncserver xfonts-base debian-properties-common gnome-flashback-classic fcitx fcitx-googlepinyin fcitx-ui-classic fcitx-frontend-gtk3 fcitx-config-gtk language-pack-zh-hans dnsutils curl sudo psmisc iputils-ping rsync netcat-openbsd whiptail bash-completion openssh-client p7zip-full iproute2 net-tools vim-tiny openssl mate-calc mate-control-center marco mate-settings-daemon caja caja-open-terminal engrampa mate-terminal pluma eom mate-system-monitor mate-session-manager pavucontrol light-themes xinput scrot upower fonts-wqy-microhei libgdk-pixbuf2.0-bin gir1.2-gtk-3.0 xdg-utils python3-gi vala-panel2 novnc -y --no-install-recommends; do true; done && apt-clean


RUN /bin/echo -e 'set backspace=indent,eol,start\nset nocompatible\nset ts=4' >> /etc/vim/vimrc.tiny
RUN rm -rf /etc/apt/apt.conf.d/docker-*

RUN locale-gen en_US.UTF-8
RUN locale-gen zh_CN.UTF-8

ENV LANG=zh_CN.UTF-8
ENV INIT_PASS=123456
ENV GEOMETRY=1400x900
ENV USER=docker

EXPOSE 5901/tcp 8443/tcp

RUN /bin/echo -e '#!/bin/bash\nrsync -Ha /etc/skel/.??* /root; [ -e /self.pem ] || yes "" | openssl req -new -x509 -days 365 -nodes -out /self.pem -keyout /self.pem\nmkdir -p ~/.vnc\necho "${INIT_PASS}" | vncpasswd -f > ~/.vnc/passwd && chmod 0600 ~/.vnc/passwd' > /usr/bin/set_vncpasswd && chmod a+x /usr/bin/set_vncpasswd
RUN /bin/echo -e '#!/bin/bash\nexec mate-session &\nwhile true; do sleep 1; caja --force-desktop -n; done\n' > /usr/bin/xstartup && chmod a+x /usr/bin/xstartup
RUN ln -sf vnc.html /usr/share/novnc/index.html
RUN rm -f /usr/bin/mate-session-save

CMD ["bash", "-c", "mkdir -p /root/.vnc && cp /usr/bin/xstartup /root/.vnc && set_vncpasswd && vncserver -geometry ${GEOMETRY} -depth 24 :1 && /usr/share/novnc/utils/novnc_proxy --vnc 0.0.0.0:5901 --listen 8443"]
